### ISSUE TITLE
Cannot compile on FreeBSD 13.2

### ISSUE THREAD

**Issue by lezzercringe** [hashlag/dm-semester-2#6]
After recent update FreeBSD 13.1 -> 13.2 compilation is constantly interrupted with panic. 

Attaching here the build log: 
[log.txt](https://github.com/hashlag/dm-semester-2/files/14792727/log.txt)

**Comment by kimvalerie** [comment]
delete your computer

**Comment by lezzercringe** [comment]
problem fixed thx @kimvalerie
